// layout.tsx
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const title = metadata.title ?? '';
  const description = metadata.description ?? '';
  return (
    <>
      <React.Fragment>
        <title>{title}</title>
        <meta name="description" content={description} />
      </React.Fragment>
      <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      />
      <body className={inter.className}>
        <header>
          {/* Header content, if any, can go here */}
        </header>
        <main>{children}</main>
      </body>
    </>
  );
}
