/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WheresReligionRouteImport } from './routes/wheres-religion'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as AuthenticatedInstructorDashboardRouteImport } from './routes/_authenticated/instructor-dashboard'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes.index'

const WheresReligionRoute = WheresReligionRouteImport.update({
  id: '/wheres-religion',
  path: '/wheres-religion',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInstructorDashboardRoute =
  AuthenticatedInstructorDashboardRouteImport.update({
    id: '/instructor-dashboard',
    path: '/instructor-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirm': typeof ConfirmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wheres-religion': typeof WheresReligionRoute
  '/instructor-dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/notes/$id': typeof NotesIdRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/confirm': typeof ConfirmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wheres-religion': typeof WheresReligionRoute
  '/instructor-dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/notes/$id': typeof NotesIdRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/confirm': typeof ConfirmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/verify-email': typeof VerifyEmailRoute
  '/wheres-religion': typeof WheresReligionRoute
  '/_authenticated/instructor-dashboard': typeof AuthenticatedInstructorDashboardRoute
  '/notes/$id': typeof NotesIdRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/confirm'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/stories'
    | '/verify-email'
    | '/wheres-religion'
    | '/instructor-dashboard'
    | '/notes/$id'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/confirm'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/stories'
    | '/verify-email'
    | '/wheres-religion'
    | '/instructor-dashboard'
    | '/notes/$id'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/confirm'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/reset-password'
    | '/resources'
    | '/signup'
    | '/stories'
    | '/verify-email'
    | '/wheres-religion'
    | '/_authenticated/instructor-dashboard'
    | '/notes/$id'
    | '/_authenticated/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  ConfirmRoute: typeof ConfirmRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  StoriesRoute: typeof StoriesRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WheresReligionRoute: typeof WheresReligionRoute
  NotesIdRoute: typeof NotesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wheres-religion': {
      id: '/wheres-religion'
      path: '/wheres-religion'
      fullPath: '/wheres-religion'
      preLoaderRoute: typeof WheresReligionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/instructor-dashboard': {
      id: '/_authenticated/instructor-dashboard'
      path: '/instructor-dashboard'
      fullPath: '/instructor-dashboard'
      preLoaderRoute: typeof AuthenticatedInstructorDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedInstructorDashboardRoute: typeof AuthenticatedInstructorDashboardRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInstructorDashboardRoute: AuthenticatedInstructorDashboardRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  ConfirmRoute: ConfirmRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  StoriesRoute: StoriesRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WheresReligionRoute: WheresReligionRoute,
  NotesIdRoute: NotesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
