name: E2E Tests (DEPRECATED - Use ci-cd.yml instead)

# DISABLED: This workflow is deprecated. Use .github/workflows/ci-cd.yml instead.
# This workflow is kept for reference but will not run automatically.
on:
  workflow_dispatch:  # Only allows manual trigger, disabled from automatic runs
  # push:
  #   branches: [ main, openai_tags, memoryleak, december-sprint ]
  # pull_request:
  #   branches: [ main, openai_tags, memoryleak, december-sprint ]

permissions:
  contents: read
  actions: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8.11.0
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      
      - name: Build the application
        run: pnpm build
        env:
          CI: true
          NEXT_PUBLIC_FIREBASE_API_KEY: ci-mock-key
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ci-mock-domain
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ci-mock-project
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ci-mock-bucket
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 123456789
          NEXT_PUBLIC_FIREBASE_APP_ID: ci-mock-app-id
          NEXT_PUBLIC_RERUM_PREFIX: ci-mock-prefix
          NEXT_PUBLIC_OPENAI_API_KEY: ci-mock-openai-key
          NEXT_PUBLIC_OPENAI_API_URL: https://api.openai.com/v1/chat/completions
      
      - name: Start the application
        run: |
          pnpm start &
          sleep 10
          timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
      
      - name: Run Playwright tests
        run: pnpm exec playwright test --project=chromium
        env:
          CI: true
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
